### ISSUE TITLE
csvpose

### ISSUE THREAD

**Issue by virtualenv** [fiblit/SimplerThanWaldo#1]
Hello,

Could you please kindly tell me where do I get the csvpose file ?

Thank you.

**Comment by fiblit** [comment]
It's a large zip file of csv files representing mocap data in a private repo of mine. If you want to make it yourself, you can convert CMU's mocap dataset of asf/amc files into the format I used here. Alternatively, record your own mocap and convert it to this format. (This format being whatever MotionParser.cpp would parse without crashing.)

This issue's repo was for a class final project a couple of years back. I only really keep this code around because it's on my resume. (Thus the lack of any license.)

I might add a permissive license to this, as well as the data files, at some point soon when I move my University's private repos to this account. If I do, I'll let you know. (But, I probably won't as this repo isn't a great example of how I code.)

**Comment by virtualenv** [comment]
Thank you so much for your reply.

Looking forward.

Best regards.
